version: 0.2

env:
  variables:
    IMAGE_TAG: latest
  parameter-store:
    ECR_REPO_URI: "/codepipeline/ecr_repo_uri"  # Store ECR repo URI securely in SSM Parameter Store

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing Terraform..."
      - curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip && mv terraform /usr/local/bin/ && terraform --version
      - echo "Installing Node.js dependencies..."
      - npm install
      - echo "Installing React dependencies..."
      - cd client && npm install && cd ..
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Checking if ECR repository exists..."
      - aws ecr describe-repositories --repository-names $ECR_REPO_URI || aws ecr create-repository --repository-name $ECR_REPO_URI
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Image tag will be $IMAGE_TAG"
  build:
    commands:
      - echo "Starting build phase..."
      - echo "Building Docker image for Node.js + React app..."
      - docker build --build-arg NODE_ENV=production -t $ECR_REPO_URI:$IMAGE_TAG .
      - echo "Running unit tests..."
      - npm test || echo "Tests completed"
  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo "Creating imagedefinitions.json for ECS deployment..."
      - printf '[{"name":"app","imageUri":"%s"}]' $ECR_REPO_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json